name: Release Feature Branch

on:
  push:
    branches-ignore:
      - main
      - develop

env:
  BOT_NAME: nr-opensource-bot
  BOT_EMAIL: opensource+bot@newrelic.com

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Ensure lerna can do the proper version bump
          # https://github.com/lerna/lerna/issues/2542
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Configure NPM
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc

      - name: Lerna Publish
        env:
          GIT_AUTHOR_NAME: Ruairi Douglas
          GIT_AUTHOR_EMAIL: ruairidouglas@gmail.com
          GIT_COMMITTER_NAME: Ruairi Douglas
          GIT_COMMITTER_EMAIL: ruairidouglas@gmail.com
          GH_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
        run: yarn release --canary minor
